apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: boss-facade
  name: boss-facade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boss-facade
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: boss-facade
    spec:
      imagePullSecrets:
        - name: devsecret
      containers:
        - image: 10.136.30.167:10009/citc-nce/boss-facade:v1-0721.1
          name: boss-facade
          ports:
            - name: "boss-8102"
              containerPort: 8102
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: 0.5
              memory: "512Mi"
          env:
            - name: NACOS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_SERVER
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_NAMESPACE
            - name: NACOS_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_USER
            - name: NACOS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_PASSWORD
status: {}