spring:
  application:
    name: chatbot-web-facade
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
        namespace: ${NACOS_NAMESPACE:05a4b74a-59e0-4867-9faa-c05fdbf5180f}
        username: ${NACOS_USER:nacos}
        password: ${NACOS_PASSWORD:nacos}
        register-enabled: ${NACOS_REGISTER_ENABLE:true}
      config:
        server-addr: ${NACOS_SERVER}
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: ${NACOS_NAMESPACE:05a4b74a-59e0-4867-9faa-c05fdbf5180f}
        username: ${NACOS_USER:nacos}
        password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - optional:nacos:chatbot-web-facade.yaml
      - optional:nacos:nce-common.yaml
      - optional:nacos:sentinel-circuitbreaker-rules.yml
server:
  port: 8100
  #address: 0.0.0.0