apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: callback-service
  name: callback-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callback-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: callback-service
    spec:
      imagePullSecrets:
        - name: devsecret
      containers:
        - image: 10.136.30.167:10009/citc-nce/callback-service:v1-0721.1
          name: callback-service
          ports:
            - name: "http-8104"
              containerPort: 8104
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: 0.5
              memory: "512Mi"
          env:
            - name: NACOS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_SERVER
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_NAMESPACE
            - name: NACOS_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_USER
            - name: NACOS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_PASSWORD

status: {}