apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nce-robot-files-provider
  name: nce-robot-files-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nce-robot-files-provider
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nce-robot-files-provider
    spec:
      imagePullSecrets:
        - name: devsecret
      containers:
        - image: 10.136.30.167:10009/citc-nce/nce-robot-files-provider:v1-0721.1
          name: nce-robot-files-provider
          ports:
            - name: "http-8210"
              containerPort: 8210
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: 0.5
              memory: "512Mi"
          env:
            - name: NACOS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_SERVER
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_NAMESPACE
            - name: NACOS_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_USER
            - name: NACOS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-server-info
                  key: NACOS_PASSWORD
status: {}
