spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: authcenter-facade
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
        namespace: ${NACOS_NAMESPACE:05a4b74a-59e0-4867-9faa-c05fdbf5180f}
        username: ${NACOS_USER:nacos}
        password: ${NACOS_PASSWORD:nacos}
        register-enabled: ${NACOS_REGISTER_ENABLE:true}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: ${spring.cloud.nacos.discovery.namespace}
        username: ${NACOS_USER:nacos}
        password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - optional:nacos:authcenter-facade.yaml
      - optional:nacos:nce-common.yaml
      - optional:nacos:sentinel-circuitbreaker-rules.yml
server:
  port: 8103
